### ISSUE TITLE
Document to specify the maven version requirement

### ISSUE THREAD

**Issue by loomlike** [microsoft/masc#19]
(On CentOS)
`sudo yum install maven` installs maven version **3.0.5** and I got this error while building a jar:

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile (default) on project accumulo-spark-datasource: The plugin net.alchim31.maven:scala-maven-plugin:4.2.0 requires Maven version 3.3.9 -> [Help 1]
```

I followed [this link](https://gist.github.com/miroslavtamas/cdca97f2eafdd6c28b844434eaa3b631) to install mvn **3.3.9** and now could build without errors.

**Comment by gramhagen** [comment]
the readme has been updated for the maven version
