### ISSUE TITLE
Dependency convergence error

### ISSUE THREAD

**Issue by phrocker** [microsoft/masc#27]
Add dependency convergence enforcer and resolve issues

**Comment by eisber** [comment]
So I enabled that and now I'm getting warnings from accumulo-core:2.0.0

Dependency convergence error for org.checkerframework:checker-qual:2.6.0 paths to dependency are:
+-com.microsoft.masc:accumulo-spark-datasource:1.0.0-SNAPSHOT
  +-org.apache.accumulo:accumulo-core:2.0.0
    +-com.github.ben-manes.caffeine:caffeine:2.7.0
      +-org.checkerframework:checker-qual:2.6.0
and
+-com.microsoft.masc:accumulo-spark-datasource:1.0.0-SNAPSHOT
  +-org.apache.accumulo:accumulo-core:2.0.0
    +-com.google.guava:guava:28.0-jre
      +-org.checkerframework:checker-qual:2.8.1
